@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho

interface Iterable {
    Iterator<Etape> iterator()
}

package "twisk" #FFFBF0 {

    package "exceptions" #FFCC99 {
        Exception MondeException
        Exception TwiskArcException
        Exception TwiskException
        Exception TwiskJetonsException
        Exception TwiskMenuException
    }

    package "monde" #FF686B {

        'Liens entre les classes
        Iterable <|.. Monde
        Iterable <|.. GestionnaireEtapes
        Iterable <|.. Etape

        Monde -right-"1" "GestionnaireEtapes" : lesEtapes
        Monde --"1" "SasEntree" : Entrée
        Monde --"1" "SasSortie" : Sortie

        Etape "*"-left-"1" GestionnaireEtapes
        Etape <|-- Activite
        Etape <|-- Guichet

        Activite <|-- SasEntree
        Activite <|-- SasSortie
        Activite <|-- ActiviteRestreinte

        'Définition des classes

        class Activite {
            - int temps
            - int ecartTemps
            + Activite(String nom)
            + Activite(String nom, int temps, int ecartTemps)
            + boolean estUneActivite()
            + boolean estUneEntree()
            + boolean estUneSortie()
            + String toString()
            + String toC()
            + int getTemps()
            + int getEcartTemps()
            + int getNbJetons()
        }

        class ActiviteRestreinte {
            + ActiviteRestreinte(String nom)
            + ActiviteRestreinte(String nom, int temps, int ecartTemps)
        }

        abstract class Etape {
            - String nom
            - int idEtape
            + Etape(String nom)
            + int getNumero()
            + void ajouterSuccesseur(Etape... e)
            + int nbSuccesseur()
            + Etape getSuccesseur(int index)
            + boolean estUneActivite()
            + boolean estUnGuichet()
            + int getNumeroSemaphore()
            + Iterator<Etape> iterator()
            + String getNom()
            + GestionnaireEtapes getEtapes()
            + String replaceCarac(String chaine)
            + {abstract} String toString()
            + {abstract} String toC()
            + {abstract} int getTemps()
            + {abstract} int getEcartTemps()
            + {abstract} int getNbJetons()
        }

        class GestionnaireEtapes {
            + GestionnaireEtapes()
            + void ajouter(Etape... etapes)
            + int nbEtapes()
            + Etape getEtape(int index)
            + Iterator<Etape> iterator()
        }

        class Guichet {
            - int nbJetons
            - int numeroSemaphore
            + Guichet(String nom)
            + Guichet(String nom, int nbJetons)
            + boolean estUnGuichet()
            + int getNumeroSemaphore()
            + String toString()
            + String toC()
            + int getTemps()
            + int getEcartTemps()
            + int getNbJetons()
        }

        class Monde {
            - int nbClients
            - int[] tabJetonsGuichets
            + Monde()
            + void aCommeEntree(Etape... etape)
            + void aCommeSortie(Etape... etape)
            + void ajouter(Etape... etape)
            + int nbEtapes()
            + int nbGuichets()
            + int[] getTabJetonsGuichets()
            + Etape getEntree(int i)
            + Iterator<Etape> iterator()
            + String toString()
            + String toC()
            + int nbClients()
            + void setNbClients(int nbClients)
            + String replaceCarac(String chaine)
            + Etape getEtape(int i)
            + SasEntree getSasEntree()
            + SasSortie getSasSortie()
        }

        class SasEntree {
            + SasEntree()
            + boolean estUneEntree()
            + String toString()
            + String toC()
            + int getTemps()
            + int getEcartTemps()
            + int getNbJetons()
        }

        class SasSortie {
            + SasSortie()
            + boolean estUneSortie()
            + String toString()
            + String toC()
            + int getTemps()
            + int getEcartTemps()
            + int getNbJetons()
        }
    }

    package "mondeIG" #D3B4FF {
        class ActiviteIG {
            - int delai
            - int ecart
            - boolean activiteRestreinte
            - String identifiant
            + ActiviteIG(String nom, int larg, int haut)
            + void setDelai(int delai)
            + void setEcart(int ecart) throws TwiskMenuException
            + int getDelai()
            + int getEcart()
            + int getNbJetons()
            + String getAttributs()
            + void setNom(String nom)
            + void switchActiviteRestreinte()
            + boolean estActiviteRestreinte()
            + String getIdentifiant()
            + String getType()
            + String toString()
        }

        class ArcIG {
            - boolean selection
            + ArcIG(PointDeControleIG source, PointDeControleIG dest)
            + double getDebutX()
            + double getDebutY()
            + double getFinX()
            + double getFinY()
            + PointDeControleIG getSource()
            + PointDeControleIG getDestination()
            + boolean estSelection()
            + void switchSelection()
            + boolean estEntrantDans(PointDeControleIG pdc)
            + boolean estSortantDe(PointDeControleIG pdc)
            + String toString()
        }

        abstract class EtapeIG {
            # String nom
            - int identifiant
            - double posX
            - double posY
            - int largeur
            - int hauteur
            - boolean selection
            - boolean estEntree
            - boolean estSortie
            + EtapeIG(String nom, int larg, int haut)
            + int getIdentifiantEtape()
            + String getNom()
            + double getPosX()
            + double getPosY()
            + void setPosX(double x)
            + void setPosY(double y)
            + Iterator<PointDeControleIG> iterator()
            + boolean estSelection()
            + void switchSelection()
            + boolean estEntree()
            + void switchEntree()
            + boolean estSortie()
            + void switchSortie()
            + void ajouterSuccesseur(EtapeIG e)
            + void ajouterPredecesseur(EtapeIG e)
            + ArrayList<EtapeIG> getSuccesseurs()
            + ArrayList<EtapeIG> getPredecesseurs()
            + EtapeIG premierSuccesseur(EtapeIG e)
            + String toString()
            + {abstract} boolean estActiviteRestreinte()
            + {abstract} int getDelai()
            + {abstract} int getEcart()
            + {abstract} int getNbJetons()
            + {abstract} String getAttributs()
            + {abstract} String getIdentifiant()
            + {abstract} void setNom(String nom)
            + {abstract} String getType()
        }

        class CorrespondancesEtapes {
            + CorrespondancesEtapes()
            + void ajouter(EtapeIG etapeIG, Etape etape)
            + Etape get(EtapeIG etapeIG)
            + EtapeIG get(Etape etape)
            + HashMap<Integer, EtapeIG> getHashmapIG()
            + HashMap<Integer, Etape> getHashmap()
            + String toString()
        }

        class GuichetIG {
            - int nbJetons
            - String identifiant
            - Sens sens
            + GuichetIG(String nom, int larg, int haut)
            + void setNbJetons(int nbJetons)
            + int getNbJetons()
            + void setNom(String nom)
            + String getIdentifiant()
            + boolean estActiviteRestreinte()
            + int getDelai()
            + int getEcart()
            + String getAttributs()
            + String getType()
            + String toString()
            + Sens getSens()
            + void setSensGuichet(Sens sens)
            + void ajouterClient(ClientIG client)
            + void viderClients()
            + ArrayList<ClientIG> getClients()
        }

        class MondeIG {
            + MondeIG()
            + void ajouter(String type)
            + Iterator<EtapeIG> iterator()
            + Iterator<ArcIG> iteratorArc()
            + Iterable<ArcIG> getArcsIterable()
            + HashMap<String, EtapeIG> getEtapes()
            + boolean pointsMemeEtape(PointDeControleIG pt1, PointDeControleIG pt2)
            + boolean arcExistant(PointDeControleIG pt1, PointDeControleIG pt2)
            + void arcValide(PointDeControleIG pt1, PointDeControleIG pt2) throws TwiskArcException
            + void ajouter(PointDeControleIG pt1, PointDeControleIG pt2) throws TwiskArcException
            + boolean estSelectionne(PointDeControleIG pt1)
            + void pointsSelectionne(PointDeControleIG pt1) throws TwiskArcException
            + void etapesSelection(EtapeIG etape)
            + void arcsSelection(ArcIG arc)
            + void supprimerArcsAssocies(EtapeIG etape)
            + void supprimerEtapesArcs()
            + void renommerEtape(String nom) throws TwiskMenuException
            + void deplacerEtape(String idEtape, double x, double y)
            + void deselectionnerEtapes()
            + void deselectionnerArcs()
            + void deselectionnerTout()
            + void choisirEntrees()
            + void choisirSorties()
            + boolean uneEtapeSelectionnee()
            + void definirDelai(int delai) throws TwiskMenuException
            + void definirEcart(int ecart) throws TwiskMenuException
            + void definirJetons(int jetons) throws TwiskJetonsException
            + void setClientIG(ArrayList<ClientIG> clientsIG)
            + ArrayList<ClientIG> getClientsIG()
            + String toString()
        }

        class ClientIG {
            - int numero
            - double x
            - double y
            - int couleur
            + ClientIG(int numero, double x, double y, int couleur, EtapeIG etape)
            + int getNumero()
            + double getX()
            + double getY()
            + int getCouleurClient()
            + EtapeIG getEtape()
        }

        class ArcIG {
            + ArcIG(PointDeControleIG source, PointDeControleIG dest)
            + double getDebutX()
            + double getDebutY()
            + double getFinX()
            + double getFinY()
            + PointDeControleIG getSource()
            + PointDeControleIG getDestination()
            + boolean estSelection()
            + void switchSelection()
            + String toString()
        }

        class PointDeControleIG {
            + PointDeControleIG(double x, double y, EtapeIG etape)
            + double getX()
            + double getY()
            + EtapeIG getEtape()
            + void deplacer(double deplacementX, double deplacementY)
            + String toString()
        }

        class SimulationIG {
            + SimulationIG(MondeIG monde)
            + void simuler()
            + void reagir()
            + Object getGestionnaire()
            + void introspectionSimu(Monde monde)
            - void verifierMondeIG()
            - void verifEntreePrede(EtapeIG e)
            - void verifSortieSucc(EtapeIG e)
            - void verifSortiePasSucc(EtapeIG e)
            - void verifActiviteRestreintePasEntree(EtapeIG e)
            - void verifierGuichet(EtapeIG e)
            - Monde creerMonde()
            - void succGuichetValide(EtapeIG e)
            - void identifierActiviteRestreinte(EtapeIG e)
            - boolean guichetUnSuccesseur(EtapeIG e)
            - void mondeVide()
            - boolean aEntree(EtapeIG e)
            - boolean aSortie(EtapeIG e)
            - void creationEtape(EtapeIG e, Monde monde)
            - void creationActiviteRestreinte(EtapeIG e, Monde monde)
            - void creationActivite(EtapeIG e, Monde monde)
            - void creationGuichet(EtapeIG e, Monde monde)
            - void lierSuccesseurs()
            - void ajouterEntreeSortie(EtapeIG e, Monde monde)
            - ArrayList<ClientIG> creerClientsIG(Object gestionnaire)
            - int creerCouleurClient(int numero)
            - EtapeIG correspondanceSas(String nom)
            - EtapeIG trouverEtapeIG(String nom)
            - double[] calculCoordonnees(int position, EtapeIG etapeIG)
            - void nettoyerClientsGuichets()
        }

        class SujetObserve {
            + void ajouterObservateur(Observateur v)
            + void notifierObservateurs()
        }

        '''Liens dans le package mondeIG'''
        'Liens class ArcIG
        ArcIG --"*" PointDeControleIG

        'Liens class CorrespondancesEtapes
        CorrespondancesEtapes --"*" EtapeIG
        CorrespondancesEtapes --"*" Etape

        'Liens class EtapeIG
        EtapeIG <|-down- ActiviteIG
        EtapeIG --"*" PointDeControleIG : pdc
        EtapeIG --"*" EtapeIG : successeurs
        EtapeIG --"*" EtapeIG : predecesseurs
        EtapeIG --> PointDeControleIG

        'Liens class GuichetIG
        GuichetIG --|> EtapeIG

        'Liens class MondeIG
        MondeIG --"*" EtapeIG : etapes
        MondeIG --"*" EtapeIG : etapesSelectionnes
        MondeIG --"*" ArcIG : arcs
        MondeIG --"*" ArcIG : arcsSelectionnes
        MondeIG --"*" PointDeControleIG : pointsSelectionnes

        'Liens class PointDeControleIG
        PointDeControleIG -- EtapeIG

        'Liens class SimulationIG
        SimulationIG -- "1" MondeIG
        SimulationIG -- "1" CorrespondancesEtapes
        SimulationIG --"1" Object : instance
        SimulationIG --"1" ClassLoaderPerso : clp
        SimulationIG --"1" Method : setNbClient
        SimulationIG --"1" Method : simuler


        '''Liens du diagramme IG'''
        VueEtapeIG --"1" Label
        VueActiviteIG --"1" HBox
        VueMondeIG --|> Pane
        VueOutils --|> TilePane
        VueOutils -- "*" Button

        Button -down- "*" EventHandler : "       "

        EcouteurBouton ..|> EventHandler
        EcouteurBouton --"1" MondeIG

        VueEtapeIG - "1" EtapeIG

        SujetObserve "1"-right "*" Observateur

        '''Fin des liens diagramme IG'''
    }

    package outils #F8FFE5 {
        class ClassLoaderPerso {
            + ClassLoaderPerso(ClassLoader parent)
            + Class loadClass(String name) throws ClassNotFoundException
            - Class getClass(String name)
            - byte[] loadClassData(String name) throws IOException
        }

        class FabriqueIdentifiant {
            - {static} FabriqueIdentifiant instance
            - int noEtape
            - int noActivite
            - int noIdentifiantPDC
            - int noIdentifiantGuichet
            + FabriqueIdentifiant()
            + {static} FabriqueIdentifiant getInstance()
            + int getIdentifiantEtape()
            + String getIdentifiantActivite()
            + String getIdentifiantPDC()
            + String getIdentifiantGuichet()
            + void reset()
        }

        class FabriqueMonde {
            + {static} Monde fabriqueMondeBasique()
            + {static} Monde fabriqueMondeBifurc()
            + {static} Monde mondeBifurc()
        }

        class FabriqueMondeIG {
            + {static} MondeIG fabriqueMondeBase()
        }

        class FabriqueNumero {
            - {static} FabriqueNumero instance
            - int cptEtape
            - int cptSemaphore
            - int cptSimulation
            - FabriqueNumero()
            + {static} FabriqueNumero getInstance()
            + int getNumeroEtape()
            + int getNumeroSemaphore()
            + int getNumeroSimulation()
            + void reset()
        }

        class KitC {
            + KitC()
            + void creerEnvironnement()
            + void creerFichier(String codeC)
            + void compiler()
            + void construireLabBibliotheque(String nomBibliotheque)
        }

        class TailleComposants {
            + {static} final int LARGEUR_FENETRE
            + {static} final int HAUTEUR_FENETRE
            + {static} final int MARGE_BAS
            + {static} final int LARGEUR_ETAPE
            + {static} final int HAUTEUR_ETAPE
            + {static} final int HAUTEUR_MINI_ACT
            + {static} final int LARGEUR_GUICHET
            + {static} final int HAUTEUR_GUICHET
            + {static} final int HAUTEUR_MINI_GUI
            + {static} final int PADDING_X
            + {static} final int PADDING_Y
            + {static} final int PADDING_SPACING
            + {static} final int MARGE_X_SUP
            + {static} final int RAYON_PDC
            + {static} final int DECAL_ARC
            + {static} final int LONG_FLECHE
            + {static} final double ANGLE_FLECHE
            + {static} final int HAUTEUR_MENU
        }

        class ThreadsManager {
            - static ThreadsManager instance
            - ArrayList<Thread> lesThreads
            + ThreadsManager()
            + static ThreadsManager getInstance()
            + void lancer(Task task)
            + void detruireTout()
        }

        FabriqueIdentifiant -- "1" FabriqueIdentifiant
    }

    package "simulation" #EDB458 {
        class "Monde" as sMonde {}
        Simulation --"1" sMonde

        class Client {
            - int numeroClient
            - int rang
            + Client(int numero)
            + int getNumeroClient()
            + int getRang()
            + Etape getEtape()
        }
        Client -- Etape

        class GestionnaireClients {
            + GestionnaireClients()
            + void setClients(int... tabClients)
            + void allerA(int numeroClient, Etape etape, int rang)
            + void nettoyer()
            + Iterator<Client> iterator()
        }
        GestionnaireClients -- "*" Client

        class Simulation {
            - int TMP_ATTENTE
            - int nbCLients
            - String nomBibliotheque
            + Simulation()
            + void simuler(Monde monde)
            + void setNbClients(int nbClients)
            + void setNomBibliotheque(String nom)
            + void afficher_info_simu(int nb_client, int nb_guichet, int nb_etape , int[] tabJetonsGuichets)
            + void afficher_pid_client(int[] tabPid, int nb_client)
            + void simule_clients(int nb_client, int nb_etape, Monde monde)
            + void lancerSimulation(Monde monde)
            + GestionnaireClients getGestionnaireClients()
            - void checkOSBibliotheque()
            - String[] initialiserNomEtapes(Monde monde, int nb_etape)
            - void afficherClients(int[] position, String[] nomEtapes, Monde monde, int nb_client)
            - void afficherEtatGestionnaire()
            - GestionnaireClients getGestionnaireClients()
        }
    }

    package vues #A3D8FF {
        interface EventHandler <<java>>

        interface Observateur {
            + void reagir()
        }

        class VBox<<java>>
        class HBox<<java>>
        class EcouteurBouton
        class Button<<java>>
        class TilePane<<java>>
        class Pane<<java>>
        class Label<<java>>

        class VueActiviteIG extends VueEtapeIG {
            + VueActiviteIG(MondeIG monde, EtapeIG etape)
        }

         class VueArcIG {
            + void VueArcIG(ArcIG arc, MondeIG monde)
            - void creerTeteFleche(double debutX, double debutY, double finX, double finY)
            - void updateCouleurSelection()
         }

         class VueClientIG extends Circle {
            + VueClientIG(ClientIG client)
         }

        abstract class VueEtapeIG extends VBox {
            + VueEtapeIG(MondeIG monde, EtapeIG etape)
            - void updateCouleurSelection()
            - void updateIcone()
        }

        class VueGuichetIG {
            + VueGuichetIG(MondeIG monde, EtapeIG etape)
            + GuichetIG getEtape()
            + void ajouterClientCase(int position, VueClientIG client)
            - void ajouterClientSelonSens(int position, VueClientIG client)
            - void afficherClients(ArrayList<ClientIG> clients)
            - void viderCases()
            - void initialiserCases()
        }

        class VueMenu {
            + VueMenu(MondeIG monde, Stage stage) throws IOException
            + void reagir()
            - void initialiserImages(MenuItem quitter, MenuItem supprimer, MenuItem renommer, MenuItem desactiverSelection, MenuItem entree, MenuItem sortie, MenuItem delai, MenuItem ecart, MenuItem jetons, MenuItem pastel, MenuItem vanille)
            - void initialiserEvenements(MenuItem quitter, MenuItem supprimer, MenuItem renommer, MenuItem desactiverSelection, MenuItem entree, MenuItem sortie, MenuItem delai, MenuItem ecart, MenuItem jetons, MenuItem pastel, MenuItem vanille)
            - String dialogueRenommerActivite()
            - int dialogueDelaiEcart() throws TwiskMenuException
            - void afficherErreur(String message)
            - int dialogueJetons()
            - void updateMenuItems()
            - void appliquerStyle(Scene scene, String cheminCSS)
            - void supprimerFichierTemp() throws IOException
        }

        class VueMondeIG implements Observateur {
            + VueMondeIG(MondeIG monde)
            - void afficherPointDeControle(EtapeIG etape)
            - void afficherArcs()
            - void afficherEtapes()
            - void afficherClientsActivite()
            - void afficherClientsGuichets()
            + void reagir()
        }

        class VueOutils implements Observateur {
            + VueOutils(MondeIG monde, SimulationIG simulation)
            + void reagir()
            - void createButtonAjouterActivite()
            - void createButtonAjouterGuichet()
            - void createButtonSimulation()
        }

        class VuePointDeControleIG {
            + void VuePointDeControleIG(PointDeControleIG pointDeControle, MondeIG monde)
            - void afficherErreur(String message)
            - void updateStyle()
        }
    }

    class ClientTwisk
    class MainTwisk
}

skinparam {
    BackgroundColor #EAE8FF
}

skinparam class {
    BackgroundColor aliceblue
    BorderColor black
}

@enduml